### ISSUE TITLE
OCI.PSModules.Common.format.ps1xml is not digitally signed. You cannot run this script on the current system

### ISSUE THREAD

**Issue by Strongarm1** [oracle/oci-powershell-modules#25] opened 2021-02-08 19:22 UTC
When system has ExecutionPolicy of RemoteSigned the scripts cannot run.
Please sign the modules so they can be used.

**Comment by joshunter** [comment] 2021-02-16 22:58
Hi @Strongarm1, thank you for the input. I'm looking into resolving this soon.

**Comment by joshunter** [comment] 2021-02-22 23:53
Hi @Strongarm1, as of now, I have not been able to replicate this issue based on the information you've provided. Would you please provide more details on how you're using the modules and the error(s) or behavior you're seeing. Thanks!

**Comment by Strongarm1** [comment] 2021-02-23 01:11
I’ll check tomorrow when I am at work.

Just tried it on my home machine with remote signed and I had no problem.

**Comment by joshunter** [comment] 2021-03-03 22:14
Hi @Strongarm1, I just wondered if you had any updates. It seems you were able to run the modules using the RemoteSigned policy on your home machine--I was not able to reproduce the error either. If there are no updates in the coming week, I'll be closing this issue. Thanks!

**Comment by joshunter** [comment] 2021-03-11 23:02
@Strongarm1, it looks like there are no updates. I'll be closing this issue but feel free to open it again if you need. Thanks!

**Closed by joshunter** 2021-03-11 23:02 UTC
Labels: SDK
